version: '3.9'

services:
  mkdocs:
    build:
      dockerfile: .docker/Dockerfile
      context: .
    volumes:
      - ./docs/:/docs/docs
      - ./mkdocs.yml:/docs/mkdocs.yml
    ports:
      - '18005:8000'
